---
title: "Combine dataframes with inner join in polars"
subtitle: "inner join"
author: '{{< var author >}}'
date: '2025-07-22'
date-format: iso
toc: true
toc-title: 'Sections'
toc-location: right
toc-depth: 3
categories: [100DaysOfPolars]
---

Just like in SQL, it's possible to join two dataframes in Polars. In this article, I'll show you how to use the `inner` join in Polars to create a dataframe with more columns. Below is a dataframe, **movies_df**, showing finance movies.

```{python}
#| echo: false
import polars as pl

movies = (pl.scan_csv('https://raw.githubusercontent.com/jorammutenge/IS537-Project/refs/heads/master/f_csv/finance_movies.csv')
 .select(pl.exclude('script','description'))
 .collect()
 .sample(4, seed=31)
 )

movies_df = (movies
 .select(pl.exclude('minutes'))
 )
movies_df
```
And here's another dataframe, **minutes_df**, showing the duration of the movies.

```{python}
#| echo: false
minutes_df = (movies
 .select('movie','minutes')
 )
minutes_df
```

## Join dataframes

You can use the `inner` join to get all the rows that match in both dataframes based on a column you choose as the key. In this case, the key column is *movie*.

```{python}
(movies_df
 .join(minutes_df, on='movie', how='inner')
 )
```
Now we have a single dataframe that contains all four columns.

::: {.callout-tip title="**Other joins you'll use**"}
Polars supports several other joins, such as:

* `left` join - Keeps all rows from the left dataframe, even those without a match, and includes only matching rows from the right dataframe. Polars does not support a right join directly, but you can achieve the same result by swapping the dataframes.
* `anti` join - Similar to a set difference in mathematics. It removes matching rows from the left dataframe.
:::

Improve your Polars skills by taking this {{< var polars_course >}}. See you in class.