project:
  type: website
  render:
    - "blog/**/*.qmd"
    - "index.qmd"
  output-dir: docs

website:
  title: "Conterval"
  favicon: images/favicon.png
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: blog/index.qmd
        text: Blog
  page-footer: 
    background: light
    center: © 2024 Conterval · [Contact](mailto:contact@conterval.com)

format:
  html:
    theme: [cosmo, custom.scss]
    css: styles.css
    code-block-border-left: true
    toc: true
    smooth-scroll: true
    link-external-newwindow: true


editor: visual

extra-files:
  - CNAME

execute:
  freeze: auto

