project:
  type: website
  render:
    - "*.qmd"
    - "blog/**/*.qmd"
    - "!polars-book/**"  # Exclude the book source files
  pre-render:
    - ./render-book.sh
  output-dir: docs

website:
  favicon: images/favicon.png
  site-url: https://www.conterval.com
  page-navigation: true
  google-analytics: 
    tracking-id: "G-5Y1ZXKXMBX"
    anonymize-ip: true
  navbar:
    left:
      - text: '{{< fa home >}}'
        href: https://www.conterval.com
      - href: blog/index.qmd
        text: Blog
      - href: books.qmd
        text: Books
      - href: media.qmd
        text: Media
      - href: https://www.udemy.com/user/joram-mutenge/
        text: Courses
        target: _blank
      - text: '{{< fa brands linkedin >}}'
        href: https://www.linkedin.com/in/jorammutenge/
        target: _blank
      - text: '{{< fa brands bluesky >}}'
        href: https://bsky.app/profile/jorammutenge.com
        target: _blank
  page-footer: 
    background: light
    center: © 2026 Conterval · [Contact](mailto:contervalconsult@gmail.com)

format:
  html:
    theme: [cosmo, custom.scss]
    css: styles.css
    code-block-border-left: true
    toc: true
    smooth-scroll: true
    link-external-newwindow: true

editor: source

extra-files:
  - CNAME

execute:
  freeze: auto