project:
  type: website
  title: Conterval
  render:
    - "blog/**/*.qmd"
    - "index.qmd"
  output-dir: docs

website:
  # title: "Conterval"
  favicon: images/favicon.png
  site-url: https://www.conterval.com
  page-navigation: true
  google-analytics: 
    tracking-id: "G-5Y1ZXKXMBX"
    anonymize-ip: true
  navbar:
    left:
      - href: blog/index.qmd
        text: Blog
  page-footer: 
    background: light
    center: © 2024 Conterval · [Contact](mailto:contact@conterval.com)

format:
  html:
    theme: [cosmo, custom.scss]
    css: styles.css
    code-block-border-left: true
    toc: true
    smooth-scroll: true
    link-external-newwindow: true


editor: source

extra-files:
  - CNAME

execute:
  freeze: auto

