---
title: "Checking the number of columns in your dataframe in polars"
subtitle: "width"
author: '{{< var author >}}'
date: '2025-08-02'
date-format: iso
toc: true
toc-title: 'Sections'
toc-location: right
toc-depth: 3
categories: [100DaysOfPolars]
---

Sometimes your dataset may have too many columns to display on the screen at once. However, you might still want to know how many columns it contains. The Polars dataframe has a property called `width` that returns the number of columns. Below is a dataframe with too many columns to display all at once.

```{python}
#| echo: false
import polars as pl

df = (pl.read_csv('https://raw.githubusercontent.com/chris1610/pbpython/refs/heads/master/data/cereal_data.csv')
#  .select(pl.nth(list(range(1,9))))
 )
df
```
<br>

## Check column count

Here's how you can check the number of columns in your dataframe:

```{python}
df.width
```

## Real world usage

You might say that the dataframe already displays the number of columns at the top. However, there may be situations where you need to check whether two dataframes have the same number of columns before concatenating them. This is where the `width` property becomes useful. When automating your process, you won’t be able to visually inspect the shapes of the dataframes, so checking their column counts programmatically is essential.

Over 100 students have enrolled in my {{< var polars\_course >}}. I encourage you to do the same.
