---
title: "Collect text data into a list in polars"
subtitle: "implode"
author: '{{< var author >}}'
date: '2025-08-14'
date-format: iso
toc: true
toc-title: 'Sections'
toc-location: right
toc-depth: 3
categories: [100DaysOfPolars]
---

Long format data (data with many rows) is good for performing analyses but bad for presentation. If you want people to easily understand your data, you should strive to reduce the length of the dataframe. Below is a dataframe showing students and the subjects they take.

```{python}
#| echo: false
import polars as pl
df = pl.DataFrame({
    "Student": ["Spencer", "Spencer", "Emily", "Emily", "Hannah", "Hannah", "Aria", "Aria"],
    "Subject": ["Chemistry", "Physics", "Physics", "Biology", "History", "Art", "English", "Biology"]
})
df
```

::: {.callout-note}
The student’s name is repeated in each row for every subject she takes. This is what it means to have long format data.
:::

## Show subjects in list

Instead of repeating the name of every student for each subject they take, let’s show the student’s name only once and collect the subjects she takes in a list. We can achieve this using the Polars expression `implode`, but first, we must group the data by *Student* to ensure each student appears only once.

```{python}
(df
 .group_by('Student')
 .agg(pl.col('Subject').implode())
 )
```
<br>

I'd appreciate it if you checked out my {{< var polars_course >}}.
