---
title: "How to remove whitespace in column values using polars in python"
subtitle: "strip_chars"
author: '{{< var author >}}'
date: '2025-06-18'
date-format: iso
toc: true
toc-title: 'Sections'
toc-location: right
toc-depth: 3
categories: [100DaysOfPolars]
---


In data science or data analysis, counting unique values is very common. However, having whitespace (empty space at the beginning or at the end) in your values can lead to inaccurate counts.

Whitespace can end up in your dataset, especially when the data is entered manually. A data entry person might press the spacebar before or after typing a value.

## Dataframe with whitespace in values
Let me show you an example of a dataframe containing values with whitespace. The first two values in *Items_Bought* contain whitespace.

```{python}
#| echo: false
import polars as pl

df = pl.DataFrame({
    'Name': ['Jeremie', 'Ashwine', 'Joram', 'Ollie', 'Jeremie', 'Ashwine', 'Joram', 'Ollie'],
    'Items_Bought': ['Apples   ', '   Milk', 'Bread', 'Eggs', 'Bananas', 'Cheese', 'Milk', 'Apples']
})

df
```

## Show unique values
Now let's show the unique items in the *Items_Bought* column.

```{python}
(df
 .select('Items_Bought')
 .unique()
 )
```

<br>
We know that "   Milk" and "Milk" are the same item, but the computer doesn't realize this. The presence of whitespace makes the values different.

## True unique values
To get the true unique values, we need to remove the whitespace from the values. Polars has a handy function that can help with this known as `strip_chars`.

```{python}
(df
 .select('Items_Bought')
 .with_columns(pl.col('Items_Bought').str.strip_chars())
 .unique()
 )
```

<br>
See how the number of values has decreased from 8 to 6? That's because "   Milk" and "Milk" are now counted as the same item.

Whenever you want to count the number of unique values in a column, it's good practice to remove any whitespace. This ensures you get an accurate count of the unique values.

Learn more in my {{< var polars_course>}}!