---
title: "How to sample data with polars"
subtitle: "sample"
author: '{{< var author >}}'
date: '2025-07-10'
date-format: iso
toc: true
toc-title: 'Sections'
toc-location: right
toc-depth: 3
categories: [100DaysOfPolars]
---

Analyzing a very large dataset can be strenuous on your computer, especially if you don't have a fast machine. Instead of overworking your computer and waiting a long time to see the results, you can perform your analysis on a smaller subset of the data. Below is a dataframe with 1000 rows.

```{python}
#| echo: false
import polars as pl

df = (pl.read_csv('https://raw.githubusercontent.com/jorammutenge/learn-rust/refs/heads/main/sample_sales.csv')
      .select('category','quantity')
      )
df
```

## Getting a subset of the data

Say we want to reduce the size of the dataset to 100 rows for faster analysis. A poor way to get those 100 rows would be to select the first or last 100 rows. Why? Because they don't provide a true representation of the entire dataset.

For example, if the dataset had null values in the last 100 rows of the *quantity* column, you might wrongly assume that the entire column contains missing values. Conversely, if you only selected the first 100 rows, you could completely miss those null values.

## Sampling is the best method

To get a true representation of the data, you should use the `sample` function. This ensures that rows are randomly selected until you reach the desired number. Here's how to use it:

```{python}
(df
 .sample(100)
 )
```

<br>
If you want your results to be reproducible, you can use the `seed` parameter.

```{python}
(df
 .sample(100, seed=42)
 )
```

<br>
Now, whenever you run the code, you'll always get the same 100 rows.

Learn more in this {{< var polars_course >}}.