---
title: "The single most important lesson I learned from my retired boss"
author: '{{< var author >}}'
date: '2025-05-18'
date-format: iso
---

The day my boss retired, a small part of me died.

Rewind.

I thought it was just another first-screening phone call. That's what typically comes to mind when you've applied to hundreds of jobs and are hoping to hear back from only a handful of them.

“Hello,” I answered the call.

“Is this Joram Mutenge?” came the voice from the other end.

“This is he,” I answered -- and that was my first introduction to Mike.

The call was supposed to last 30 minutes; we ended up talking for an hour. When I hung up, I knew this wasn't just another first-screening phone call a job-seeker receives from a recruiter. It felt different for two reasons:

1. I was speaking directly to the hiring manager.
2. He genuinely wanted to hear my story.

After that conversation, I knew I wanted to work for this man -- and I did. Mike became my boss.

But all things, whether good or bad, must come to an end. A few weeks ago, my boss retired. When we had our last lunch together, I told him that I would miss him -- and I meant it.

Shakespeare was right when he said:

> Parting is such sweet sorrow.

It was hard to come to terms with the idea that my beloved boss would no longer be around. Still, it was a good run, and I hope his retirement is just as fun.

What I'll never forget is something he said to me almost offhandedly, but it's a piece of wisdom I'll carry with me wherever my career takes me:

> In whatever you do at work, remember to ask yourself: “Is this cutting costs or reducing time?”

That question is a powerful filter to ensure you're working on projects that truly make an impact on the business.