---
title: "Creating dummy variables in a polars dataframe"
subtitle: "to_dummies"
author: '{{< var author >}}'
date: '2025-09-12'
date-format: iso
toc: true
toc-title: 'Sections'
toc-location: right
toc-depth: 3
categories: [100DaysOfPolars]
---

Computers process numerical data faster than text data. That’s why it’s a good idea to convert text data into numerical data when training machine learning models. You want to squeeze out as much performance as possible from your machine. For instance, if you have a column *Is_Present*, instead of values like "Yes" and "No," you should use 1 and 0 respectively.

Below is a dataframe showing the computer brands and the chip used in their computer models.

```{python}
#| echo: false
import polars as pl
df = (pl.read_csv("https://raw.githubusercontent.com/jorammutenge/laptop-price/refs/heads/master/data.csv")
      .select('brand','processor_brand')
      .rename(dict(processor_brand='chip'))
      )
df
```

## Create dummy variable from chip types

To make data processing faster, we need to convert chip values into numerical data. One approach is to create a separate column for each chip type, with a value of 1 if a computer brand uses that chip and 0 if it does not. Fortunately, this is very easy to do in Polars with the `to_dummies` method.

```{python}
df.to_dummies(columns='chip')
```
Now all the chip information has been converted into zeroes and ones. For example, in the first row, Lenovo uses an AMD chip. It does not use Intel or any of the other chips.

I want you to join the 150+ students in my {{< var polars_course >}}.