---
title: "How to do grouping calculations in polars"
subtitle: "group_by"
author: '{{< var author >}}'
date: '2025-07-12'
date-format: iso
toc: true
toc-title: 'Sections'
toc-location: right
toc-depth: 3
categories: [100DaysOfPolars]
---

Aggregations to data professionals are what a saw is to a carpenter. Almost every data analysis you perform will involve an aggregate calculation, or `group_by` calculations, to use the technical term. Below is a dataframe containing 1,000 rows.

```{python}
#| echo: false
import polars as pl
df = (pl.read_csv('https://raw.githubusercontent.com/jorammutenge/learn-rust/refs/heads/main/sample_sales.csv')
      .rename({'Account Name':'acct_name'})
      .select('acct_name','category','quantity')
      )
df
```
<br>

## Aggregating numerical values

Your boss isn't interested in knowing how many sweaters Sally bought. She's interested in how many total sweaters the store sold. Here's how to perform that calculation in Polars. We'll calculate both the total and average quantity.

```{python}
(df
 .group_by('category')
 .agg(pl.sum('quantity').alias('Total_Qty'),
      pl.mean('quantity').alias('Avg_Qty'))
 )
```

## Aggregating text values

In Polars, `group_by` aggregations can also be performed on non-numerical columns. Let's consider a practical example. Suppose we wanted to know which customers bought clothing from all three categories. Here's how we would do that.

```{python}
(df
 .group_by('acct_name')
 .agg('category')
 .filter(pl.col('category').list.n_unique() == 3) # three is the max number of categories
 )
```

<br>
Now we know that 11 customers bought clothing from all three categories: hats, socks, and sweaters.

I'm looking forward to teaching you in my {{< var polars_course >}}.
