<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.26">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="">

<title>6&nbsp; Experiment Analysis – Deep Analysis with Polars</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js" integrity="sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2" crossorigin="anonymous"></script><script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./Creating Complex Datasets for Analysis.html" rel="next">
<link href="./Anomaly Detection.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-b89014556cd67d477916fb41ccd32fe9.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-ca8ae8b56efe94859b05e43d31184f34.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js" integrity="sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./Experiment Analysis.html"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Experiment Analysis</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Deep Analysis with Polars</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Analysis with Polars.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Analysis with Polars</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Preparing Data for Analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Preparing Data for Analysis</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Time Series Analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Time Series Analysis</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Text Analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Text Analysis</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Anomaly Detection.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Anomaly Detection</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Experiment Analysis.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Experiment Analysis</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Creating Complex Datasets for Analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Creating Complex Datasets for Analysis</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Bringing It All Together.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Bringing It All Together</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Conclusion.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Conclusion</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#strengths-and-limits-of-experiment-analysis-with-polars" id="toc-strengths-and-limits-of-experiment-analysis-with-polars" class="nav-link active" data-scroll-target="#strengths-and-limits-of-experiment-analysis-with-polars"><span class="header-section-number">6.1</span> Strengths and Limits of Experiment Analysis with Polars</a></li>
  <li><a href="#the-dataset" id="toc-the-dataset" class="nav-link" data-scroll-target="#the-dataset"><span class="header-section-number">6.2</span> The Dataset</a></li>
  <li><a href="#types-of-experiments" id="toc-types-of-experiments" class="nav-link" data-scroll-target="#types-of-experiments"><span class="header-section-number">6.3</span> Types of Experiments</a>
  <ul class="collapse">
  <li><a href="#experiments-with-binary-outcomes-the-chi-squared-test" id="toc-experiments-with-binary-outcomes-the-chi-squared-test" class="nav-link" data-scroll-target="#experiments-with-binary-outcomes-the-chi-squared-test"><span class="header-section-number">6.3.1</span> Experiments with Binary Outcomes: The Chi-Squared Test</a></li>
  <li><a href="#experiments-with-continuous-outcomes-the-t-test" id="toc-experiments-with-continuous-outcomes-the-t-test" class="nav-link" data-scroll-target="#experiments-with-continuous-outcomes-the-t-test"><span class="header-section-number">6.3.2</span> Experiments with Continuous Outcomes: The t-Test</a></li>
  </ul></li>
  <li><a href="#challenges-with-experiments-and-options-for-rescuing-flawed-experiments" id="toc-challenges-with-experiments-and-options-for-rescuing-flawed-experiments" class="nav-link" data-scroll-target="#challenges-with-experiments-and-options-for-rescuing-flawed-experiments"><span class="header-section-number">6.4</span> Challenges with Experiments and Options for Rescuing Flawed Experiments</a>
  <ul class="collapse">
  <li><a href="#variant-assignment" id="toc-variant-assignment" class="nav-link" data-scroll-target="#variant-assignment"><span class="header-section-number">6.4.1</span> Variant Assignment</a></li>
  </ul></li>
  <li><a href="#outliers" id="toc-outliers" class="nav-link" data-scroll-target="#outliers"><span class="header-section-number">6.5</span> Outliers</a>
  <ul class="collapse">
  <li><a href="#time-boxing" id="toc-time-boxing" class="nav-link" data-scroll-target="#time-boxing"><span class="header-section-number">6.5.1</span> Time Boxing</a></li>
  <li><a href="#repeated-exposure-experiments" id="toc-repeated-exposure-experiments" class="nav-link" data-scroll-target="#repeated-exposure-experiments"><span class="header-section-number">6.5.2</span> Repeated Exposure Experiments</a></li>
  </ul></li>
  <li><a href="#when-controlled-experiments-arent-possible-alternative-analyses" id="toc-when-controlled-experiments-arent-possible-alternative-analyses" class="nav-link" data-scroll-target="#when-controlled-experiments-arent-possible-alternative-analyses"><span class="header-section-number">6.6</span> When Controlled Experiments Aren’t Possible: Alternative Analyses</a>
  <ul class="collapse">
  <li><a href="#pre-post-analysis" id="toc-pre-post-analysis" class="nav-link" data-scroll-target="#pre-post-analysis"><span class="header-section-number">6.6.1</span> Pre-/Post-Analysis</a></li>
  <li><a href="#natural-experiment-analysis" id="toc-natural-experiment-analysis" class="nav-link" data-scroll-target="#natural-experiment-analysis"><span class="header-section-number">6.6.2</span> Natural Experiment Analysis</a></li>
  <li><a href="#analysis-of-populations-around-a-threshold" id="toc-analysis-of-populations-around-a-threshold" class="nav-link" data-scroll-target="#analysis-of-populations-around-a-threshold"><span class="header-section-number">6.6.3</span> Analysis of Populations Around a Threshold</a></li>
  </ul></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion"><span class="header-section-number">6.7</span> Conclusion</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block"><h1 class="title display-7"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Experiment Analysis</span></h1></header>

<header id="title-block-header">

<p class="author"></p>

</header>


<style>
#TOC {
  background: url("images/cover.png");
  background-size: contain;
  background-position: top center;
  background-repeat: no-repeat;
  padding-top: calc(100% * 0.5 * 3) !important; /* Adjust multiplier based on your cover's aspect ratio */
}
</style>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<p>This book is a first draft, and I am actively collecting feedback to shape the final version. Let me know if you spot typos, errors in the code, or unclear explanations, your input would be greatly appreciated. And your suggestions will help make this book more accurate, readable, and useful for others. You can reach me at:<br>
<strong>Email:</strong> <a href="mailto:contervalconsult@gmail.com" class="email">contervalconsult@gmail.com</a><br>
<strong>LinkedIn:</strong> <a href="https://www.linkedin.com/in/jorammutenge/">www.linkedin.com/in/jorammutenge</a><br>
<strong>Datasets:</strong> <a href="https://drive.google.com/file/d/1pYoiqAd-Rr3mBJ8MUADyMoRxKneA1J-h/view?usp=sharing">Download all datasets</a></p>
</div>
</div>
<div class="epigraph">
<blockquote class="blockquote">
<p>Enough A/B testing will turn any website into a porn site.</p>
</blockquote>
<div style="text-align: right">
<p>— <em>Seth Godin</em></p>
</div>
</div>
<hr>
<p><em>Experimentation</em>, often called <em>A/B testing</em> or <em>split testing</em>, is widely considered the most reliable way to establish causal relationships. Much of data analysis focuses on identifying correlations, situations in which two events or attributes tend to occur together because of behavior, shared characteristics, or seasonal patterns. You have likely heard the phrase “correlation does not equal causation,” and experimentation exists specifically to address this limitation.</p>
<p>Every experiment begins with a <em>hypothesis</em>, a prediction about how behavior will change when some aspect of a product, workflow, or communication is altered. The change might involve a redesigned interface, a revised onboarding flow, a new recommendation algorithm, updated marketing language, or many other possibilities. In principle, anything an organization owns or controls can be tested. Hypotheses often grow out of earlier analytical work. For example, if analysis shows that many users abandon a signup form partway through, a reasonable hypothesis might be that simplifying the form will increase completion rates.</p>
<p>A second essential component of an experiment is a <em>success metric</em>. The expected behavioral change may involve form submissions, purchase rates, click-throughs, user retention, engagement, or any other action tied to organizational goals. A good success metric clearly quantifies behavior, is easy to measure, and is sensitive enough to detect meaningful differences. Metrics such as click-through rate, checkout completion, or time to complete a task often meet these criteria. Other measures, including long-term retention or customer satisfaction, are important but are usually influenced by many external factors. As a result, they may not respond clearly to a single experimental change. Strong success metrics are often those already tracked as part of routine business monitoring.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>You might wonder whether an experiment can track multiple success metrics. With Polars, generating many metrics is certainly possible. However, this raises the multiple comparisons problem. Without delving into the statistics, the intuition is straightforward. The more metrics you examine, the more likely it becomes that at least one will appear significant purely by chance. If you check a single metric, you may or may not observe a meaningful difference. If you check 30, it is quite likely that one will look significant even if the experiment had no real effect. As a general guideline, select one or two primary success metrics. A small number of additional metrics, often called <em>guardrail metrics</em>, can help ensure that the experiment does not unintentionally harm something important. For example, you might verify that a new feature does not slow search results, even if speed is not the primary goal.</p>
</div>
</div>
<p>The third requirement for experimentation is a system that randomly assigns individuals or entities to a control group or a test variant and then adjusts their experience accordingly. This setup is often referred to as a <em>cohorting system</em>. Many software providers offer tools for this purpose, while some organizations build their own to gain additional flexibility. Regardless of the approach, analyzing experiments with Polars requires that assignment data be combined with behavioral data in a single dataset.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>The experiments discussed in this chapter focus on online experiments, where assignment is handled programmatically and user behavior is tracked digitally. Many scientific fields also rely on experimentation, but there is an important distinction. Online experiments typically use metrics that are already collected for other purposes, whereas scientific studies often gather data exclusively for the experiment and only during the experiment window. In online settings, it is sometimes necessary to rely on proxy metrics when direct measurement is not feasible.</p>
</div>
</div>
<p>Once you have defined a hypothesis, selected a success metric, and implemented a cohorting system, you can run experiments, collect data, and evaluate results using Polars.</p>
<section id="strengths-and-limits-of-experiment-analysis-with-polars" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="strengths-and-limits-of-experiment-analysis-with-polars"><span class="header-section-number">6.1</span> Strengths and Limits of Experiment Analysis with Polars</h2>
<p>Polars is well suited for experiment analysis. Many success metrics are already part of an organization’s analytical toolkit, with existing Polars code ready to apply. Incorporating variant assignment data into established logic is often a straightforward extension of existing workflows.</p>
<p>Polars also supports automated experiment reporting. The same analysis code can be reused across experiments by changing only the experiment name or identifier in a <code>filter</code> statement. Organizations that run many experiments often develop standardized reporting templates to streamline both analysis and interpretation.</p>
<p>One important limitation is that Polars does not compute statistical significance on its own. Libraries such as <strong>SciPy</strong> can address this gap by performing the required statistical tests. A common workflow is to calculate summary statistics in Polars and then use SciPy to assess whether observed differences are statistically significant. We won’t use SciPy in this book. Instead, we’ll use the online calculator at <a href="https://www.evanmiller.org/ab-testing/chi-squared.html">Evanmiller.org</a> to check if the experiment results are statistically significant.</p>
<!-- [^chp6-evan-chi]: https://www.evanmiller.org/ab-testing/chi-squared.html -->
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Expand Your Knowledge
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>WHY CORRELATION IS NOT CAUSATION</strong><br>
It is much easier to show that two variables move together, whether they increase, decrease, or occur at the same time, than it is to demonstrate that one causes the other. Although we naturally look for cause-and-effect explanations, there are actually five possible relationships between two variables, X and Y:</p>
<ol type="1">
<li><em>X causes Y</em>: This is the relationship we usually hope to identify. A change in X directly leads to a change in Y.</li>
<li><em>Y causes X</em>: The relationship exists, but the direction is reversed. Carrying a backpack does not cause someone to attend school. Instead, attending school leads people to carry backpacks.</li>
<li><em>X and Y share a common cause</em>: A third factor explains both variables. For example, sunscreen sales and beach attendance both increase on sunny days, but neither causes the other. The weather drives both behaviors.</li>
<li><em>X and Y influence each other</em>: A feedback loop develops. For instance, when a subscription service begins to lose a customer’s interest, the customer interacts less. This reduces the system’s ability to recommend relevant content, which further decreases engagement. Over time, it becomes difficult to identify which change initiated the cycle.</li>
<li><em>There is no real relationship</em>: Sometimes two metrics appear correlated purely by coincidence. When enough variables are examined, some apparent patterns will arise by chance alone.</li>
</ol>
</div>
</div>
</section>
<section id="the-dataset" class="level2" data-number="6.2">
<h2 data-number="6.2" class="anchored" data-anchor-id="the-dataset"><span class="header-section-number">6.2</span> The Dataset</h2>
<p>In this chapter, we work with four datasets created for a fictional online education platform called XtraLesson. The <em>students</em> dataset contains records for individuals who registered for courses, including their signup dates and countries of origin. A small preview is shown below.</p>
<div id="98570cb9" class="cell" data-execution_count="1">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> polars <span class="im">as</span> pl</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>students <span class="op">=</span> pl.read_csv(<span class="st">"data/students.csv"</span>, try_parse_dates<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>students.sample(<span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="1">
<div><style>
.dataframe > thead > tr,
.dataframe > tbody > tr {
  text-align: right;
  white-space: pre-wrap;
}
</style>
<small>shape: (3, 3)</small>
<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">User_ID</th>
<th data-quarto-table-cell-role="th">Enroll_Date</th>
<th data-quarto-table-cell-role="th">Country</th>
</tr>
<tr class="even">
<td>i64</td>
<td>date</td>
<td>str</td>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>29848</td>
<td>2024-01-17</td>
<td>"United States"</td>
</tr>
<tr class="even">
<td>53061</td>
<td>2024-01-27</td>
<td>"Mexico"</td>
</tr>
<tr class="odd">
<td>46176</td>
<td>2024-01-23</td>
<td>"United States"</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>The <em>actions</em> dataset captures the activities students perform on the XtraLesson platform. A brief sample appears here.</p>
<div id="1e97b946" class="cell" data-execution_count="2">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>actions <span class="op">=</span> pl.read_csv(<span class="st">"data/actions.csv"</span>, try_parse_dates<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>actions.sample(<span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="2">
<div><style>
.dataframe > thead > tr,
.dataframe > tbody > tr {
  text-align: right;
  white-space: pre-wrap;
}
</style>
<small>shape: (3, 3)</small>
<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">User_ID</th>
<th data-quarto-table-cell-role="th">Action</th>
<th data-quarto-table-cell-role="th">Date</th>
</tr>
<tr class="even">
<td>i64</td>
<td>str</td>
<td>date</td>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1075</td>
<td>"Tutorial complete"</td>
<td>2024-01-01</td>
</tr>
<tr class="even">
<td>77245</td>
<td>"Email opt-in"</td>
<td>2024-02-09</td>
</tr>
<tr class="odd">
<td>84066</td>
<td>"Email opt-in"</td>
<td>2024-02-12</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>The <em>payments</em> dataset records the amounts students pay for XtraLesson courses, expressed in US dollars. An example is shown below.</p>
<div id="6822117b" class="cell" data-execution_count="3">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>payments <span class="op">=</span> pl.read_csv(<span class="st">"data/payments.csv"</span>, try_parse_dates<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>payments.sample(<span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="3">
<div><style>
.dataframe > thead > tr,
.dataframe > tbody > tr {
  text-align: right;
  white-space: pre-wrap;
}
</style>
<small>shape: (3, 3)</small>
<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">User_ID</th>
<th data-quarto-table-cell-role="th">Pay_Date</th>
<th data-quarto-table-cell-role="th">Amount</th>
</tr>
<tr class="even">
<td>i64</td>
<td>date</td>
<td>f64</td>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>80659</td>
<td>2024-02-15</td>
<td>10.0</td>
</tr>
<tr class="even">
<td>100100</td>
<td>2024-02-23</td>
<td>10.0</td>
</tr>
<tr class="odd">
<td>61922</td>
<td>2024-02-20</td>
<td>10.0</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>Finally, the <em>assignments</em> dataset indicates which experimental variant each student was assigned to. A snippet of this data is provided here.</p>
<div id="8b682c7d" class="cell" data-execution_count="4">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>experiments <span class="op">=</span> pl.read_csv(<span class="st">"data/experiments.csv"</span>, try_parse_dates<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>experiments.sample(<span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="4">
<div><style>
.dataframe > thead > tr,
.dataframe > tbody > tr {
  text-align: right;
  white-space: pre-wrap;
}
</style>
<small>shape: (3, 4)</small>
<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">Experiment</th>
<th data-quarto-table-cell-role="th">User_ID</th>
<th data-quarto-table-cell-role="th">Date</th>
<th data-quarto-table-cell-role="th">Variant</th>
</tr>
<tr class="even">
<td>str</td>
<td>i64</td>
<td>date</td>
<td>str</td>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>"Welcome tutorial"</td>
<td>50405</td>
<td>2024-01-27</td>
<td>"Variant 1"</td>
</tr>
<tr class="even">
<td>"Welcome tutorial"</td>
<td>84255</td>
<td>2024-02-13</td>
<td>"Variant 1"</td>
</tr>
<tr class="odd">
<td>"Welcome tutorial"</td>
<td>57419</td>
<td>2024-01-29</td>
<td>"Variant 1"</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>All four datasets are fully synthetic. They were generated using random processes but are designed to resemble the structure and relationships found in a real-world online learning platform.</p>
</section>
<section id="types-of-experiments" class="level2" data-number="6.3">
<h2 data-number="6.3" class="anchored" data-anchor-id="types-of-experiments"><span class="header-section-number">6.3</span> Types of Experiments</h2>
<p>Experiments can take many forms. Nearly any aspect of a user’s experience, whether they are customers, members, or participants, can be modified and tested. From an analytical standpoint, experiments generally fall into two broad categories: those that measure binary outcomes and those that measure continuous outcomes.</p>
<section id="experiments-with-binary-outcomes-the-chi-squared-test" class="level3" data-number="6.3.1">
<h3 data-number="6.3.1" class="anchored" data-anchor-id="experiments-with-binary-outcomes-the-chi-squared-test"><span class="header-section-number">6.3.1</span> Experiments with Binary Outcomes: The Chi-Squared Test</h3>
<p>Binary-outcome experiments evaluate situations with only two possible results. A user either completes a registration flow or abandons it. Someone clicks an advertisement or ignores it. A learner graduates or does not. In these experiments, we compute the proportion of users in each variant who complete the action of interest. The numerator represents the number of users who performed the action, while the denominator includes all users exposed to the variant. This proportion is commonly referred to as a rate, such as a completion rate, click-through rate, or graduation rate.</p>
<p>To determine whether these rates differ meaningfully across variants, we use the <em>chi-squared test</em>, a statistical method designed for categorical data.<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> Results from this test are typically organized into a <em>contingency table</em>, which displays counts at the intersection of two categorical variables. If you have worked with pivot tables before, this layout will likely feel familiar.</p>
<p>Consider an example using the XtraLesson data. A product manager introduces a redesigned onboarding flow that guides new students through finding courses, identifying discounts, and enrolling. The objective is to encourage more students to complete onboarding and begin their first course. This redesign was evaluated in an experiment called “Welcome tutorial,” which randomly assigned students to either “Control” or “Variant 1” in the <em>experiments</em> dataset. In the <em>actions</em> dataset, the event labeled “Tutorial complete” indicates whether a student finished the onboarding flow.</p>
<p>The contingency table summarizes how many students in each variant did or did not complete the tutorial. The Polars code below computes these counts by grouping on the <em>Variant</em> column and summing the presence or absence of the “Tutorial complete” action:</p>
<div id="e6a53bad" class="cell" data-execution_count="5">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>contingency_df <span class="op">=</span> (experiments</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a> .<span class="bu">filter</span>(pl.col(<span class="st">'Experiment'</span>) <span class="op">==</span> <span class="st">'Welcome tutorial'</span>)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a> .join(actions.<span class="bu">filter</span>(pl.col(<span class="st">'Action'</span>) <span class="op">==</span> <span class="st">'Tutorial complete'</span>),</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>       on<span class="op">=</span><span class="st">'User_ID'</span>,</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>       how<span class="op">=</span><span class="st">'left'</span>)</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a> .group_by(<span class="st">'Variant'</span>)</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a> .agg(Completed<span class="op">=</span>pl.col(<span class="st">'Action'</span>).is_not_null().<span class="bu">sum</span>(),</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>      Not_Completed<span class="op">=</span>pl.col(<span class="st">'Action'</span>).is_null().<span class="bu">sum</span>())</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>contingency_df</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="5">
<div><style>
.dataframe > thead > tr,
.dataframe > tbody > tr {
  text-align: right;
  white-space: pre-wrap;
}
</style>
<small>shape: (2, 3)</small>
<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">Variant</th>
<th data-quarto-table-cell-role="th">Completed</th>
<th data-quarto-table-cell-role="th">Not_Completed</th>
</tr>
<tr class="even">
<td>str</td>
<td>u32</td>
<td>u32</td>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>"Control"</td>
<td>36268</td>
<td>13629</td>
</tr>
<tr class="even">
<td>"Variant 1"</td>
<td>38280</td>
<td>11995</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>Next, we add row and column totals to convert these results into a full contingency table:</p>
<div id="3f990627" class="cell" data-execution_count="6">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>contigency_table <span class="op">=</span> (contingency_df</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a> .rename(<span class="bu">dict</span>(Completed<span class="op">=</span><span class="st">'Yes'</span>, Not_Completed<span class="op">=</span><span class="st">'No'</span>))</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a> .vstack(pl.DataFrame({</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>     <span class="st">'Variant'</span>:<span class="st">'Total'</span>,</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>     <span class="st">'Yes'</span>: contingency_df.select(pl.<span class="bu">sum</span>(<span class="st">'Completed'</span>)),</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>     <span class="st">'No'</span>: contingency_df.select(pl.<span class="bu">sum</span>(<span class="st">'Not_Completed'</span>)),</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>     }))</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a> .with_columns(Total<span class="op">=</span>pl.sum_horizontal(pl.nth(<span class="dv">1</span>,<span class="dv">2</span>)))</span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a> )</span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>contigency_table</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="6">
<div><style>
.dataframe > thead > tr,
.dataframe > tbody > tr {
  text-align: right;
  white-space: pre-wrap;
}
</style>
<small>shape: (3, 4)</small>
<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">Variant</th>
<th data-quarto-table-cell-role="th">Yes</th>
<th data-quarto-table-cell-role="th">No</th>
<th data-quarto-table-cell-role="th">Total</th>
</tr>
<tr class="even">
<td>str</td>
<td>u32</td>
<td>u32</td>
<td>u32</td>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>"Control"</td>
<td>36268</td>
<td>13629</td>
<td>49897</td>
</tr>
<tr class="even">
<td>"Variant 1"</td>
<td>38280</td>
<td>11995</td>
<td>50275</td>
</tr>
<tr class="odd">
<td>"Total"</td>
<td>74548</td>
<td>25624</td>
<td>100172</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>Polars dataframes can be customized not only in structure but also in appearance. As a small enhancement, we can apply styling to the contingency table to improve readability. To do this, install the <strong>Great Tables</strong> library, which Polars uses for styling:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb7"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="ex">pip</span> install great-tables</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Or if using Jupyter</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a><span class="ex">!pip</span> install great-tables</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Once the library is installed, we can apply formatting to the table:</p>
<div id="b6777d6d" class="cell" data-execution_count="7">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> great_tables <span class="im">import</span> loc, style, html</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>(contigency_table</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a> .style</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a> .tab_header(title<span class="op">=</span>html(<span class="st">'&lt;b&gt;Completed tutorial?'</span>))</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a> .cols_label(Total<span class="op">=</span>html(<span class="st">'&lt;b&gt;Total'</span>))</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a> .tab_style(style<span class="op">=</span>style.text(weight<span class="op">=</span><span class="st">'bold'</span>),</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>            locations<span class="op">=</span>loc.body(rows<span class="op">=-</span><span class="dv">1</span>))</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a> .tab_style(style<span class="op">=</span>style.text(weight<span class="op">=</span><span class="st">'bold'</span>),</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>            locations<span class="op">=</span>loc.body(columns<span class="op">=</span><span class="st">'Total'</span>))</span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a> .tab_style(style<span class="op">=</span>style.text(weight<span class="op">=</span><span class="st">'bold'</span>),</span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>            locations<span class="op">=</span>loc.column_labels(columns<span class="op">=</span><span class="st">'Total'</span>))</span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a> .fmt_number(columns<span class="op">=</span>[<span class="st">'Yes'</span>, <span class="st">'No'</span>, <span class="st">'Total'</span>], decimals<span class="op">=</span><span class="dv">0</span>, use_seps<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="7">
<div id="ynvaqpxybs" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>
#ynvaqpxybs table {
          font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;
          -webkit-font-smoothing: antialiased;
          -moz-osx-font-smoothing: grayscale;
        }

#ynvaqpxybs thead, tbody, tfoot, tr, td, th { border-style: none; }
 tr { background-color: transparent; }
#ynvaqpxybs p { margin: 0; padding: 0; }
 #ynvaqpxybs .gt_table { display: table; border-collapse: collapse; line-height: normal; margin-left: auto; margin-right: auto; color: #333333; font-size: 16px; font-weight: normal; font-style: normal; background-color: #FFFFFF; width: auto; border-top-style: solid; border-top-width: 2px; border-top-color: #A8A8A8; border-right-style: none; border-right-width: 2px; border-right-color: #D3D3D3; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #A8A8A8; border-left-style: none; border-left-width: 2px; border-left-color: #D3D3D3; }
 #ynvaqpxybs .gt_caption { padding-top: 4px; padding-bottom: 4px; }
 #ynvaqpxybs .gt_title { color: #333333; font-size: 125%; font-weight: initial; padding-top: 4px; padding-bottom: 4px; padding-left: 5px; padding-right: 5px; border-bottom-color: #FFFFFF; border-bottom-width: 0; }
 #ynvaqpxybs .gt_subtitle { color: #333333; font-size: 85%; font-weight: initial; padding-top: 3px; padding-bottom: 5px; padding-left: 5px; padding-right: 5px; border-top-color: #FFFFFF; border-top-width: 0; }
 #ynvaqpxybs .gt_heading { background-color: #FFFFFF; text-align: center; border-bottom-color: #FFFFFF; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; }
 #ynvaqpxybs .gt_bottom_border { border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; }
 #ynvaqpxybs .gt_col_headings { border-top-style: solid; border-top-width: 2px; border-top-color: #D3D3D3; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; }
 #ynvaqpxybs .gt_col_heading { color: #333333; background-color: #FFFFFF; font-size: 100%; font-weight: normal; text-transform: inherit; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; vertical-align: bottom; padding-top: 5px; padding-bottom: 5px; padding-left: 5px; padding-right: 5px; overflow-x: hidden; }
 #ynvaqpxybs .gt_column_spanner_outer { color: #333333; background-color: #FFFFFF; font-size: 100%; font-weight: normal; text-transform: inherit; padding-top: 0; padding-bottom: 0; padding-left: 4px; padding-right: 4px; }
 #ynvaqpxybs .gt_column_spanner_outer:first-child { padding-left: 0; }
 #ynvaqpxybs .gt_column_spanner_outer:last-child { padding-right: 0; }
 #ynvaqpxybs .gt_column_spanner { border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; vertical-align: bottom; padding-top: 5px; padding-bottom: 5px; overflow-x: hidden; display: inline-block; width: 100%; }
 #ynvaqpxybs .gt_spanner_row { border-bottom-style: hidden; }
 #ynvaqpxybs .gt_group_heading { padding-top: 8px; padding-bottom: 8px; padding-left: 5px; padding-right: 5px; color: #333333; background-color: #FFFFFF; font-size: 100%; font-weight: initial; text-transform: inherit; border-top-style: solid; border-top-width: 2px; border-top-color: #D3D3D3; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; vertical-align: middle; text-align: left; }
 #ynvaqpxybs .gt_empty_group_heading { padding: 0.5px; color: #333333; background-color: #FFFFFF; font-size: 100%; font-weight: initial; border-top-style: solid; border-top-width: 2px; border-top-color: #D3D3D3; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; vertical-align: middle; }
 #ynvaqpxybs .gt_from_md> :first-child { margin-top: 0; }
 #ynvaqpxybs .gt_from_md> :last-child { margin-bottom: 0; }
 #ynvaqpxybs .gt_row { padding-top: 8px; padding-bottom: 8px; padding-left: 5px; padding-right: 5px; margin: 10px; border-top-style: solid; border-top-width: 1px; border-top-color: #D3D3D3; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; vertical-align: middle; overflow-x: hidden; }
 #ynvaqpxybs .gt_stub { color: #333333; background-color: #FFFFFF; font-size: 100%; font-weight: initial; text-transform: inherit; border-right-style: solid; border-right-width: 2px; border-right-color: #D3D3D3; padding-left: 5px; padding-right: 5px; }
 #ynvaqpxybs .gt_stub_row_group { color: #333333; background-color: #FFFFFF; font-size: 100%; font-weight: initial; text-transform: inherit; border-right-style: solid; border-right-width: 2px; border-right-color: #D3D3D3; padding-left: 5px; padding-right: 5px; vertical-align: top; }
 #ynvaqpxybs .gt_row_group_first td { border-top-width: 2px; }
 #ynvaqpxybs .gt_row_group_first th { border-top-width: 2px; }
 #ynvaqpxybs .gt_striped { background-color: rgba(128,128,128,0.05); }
 #ynvaqpxybs .gt_table_body { border-top-style: solid; border-top-width: 2px; border-top-color: #D3D3D3; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; }
 #ynvaqpxybs .gt_sourcenotes { color: #333333; background-color: #FFFFFF; border-bottom-style: none; border-bottom-width: 2px; border-bottom-color: #D3D3D3; border-left-style: none; border-left-width: 2px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 2px; border-right-color: #D3D3D3; }
 #ynvaqpxybs .gt_sourcenote { font-size: 90%; padding-top: 4px; padding-bottom: 4px; padding-left: 5px; padding-right: 5px; text-align: left; }
 #ynvaqpxybs .gt_left { text-align: left; }
 #ynvaqpxybs .gt_center { text-align: center; }
 #ynvaqpxybs .gt_right { text-align: right; font-variant-numeric: tabular-nums; }
 #ynvaqpxybs .gt_font_normal { font-weight: normal; }
 #ynvaqpxybs .gt_font_bold { font-weight: bold; }
 #ynvaqpxybs .gt_font_italic { font-style: italic; }
 #ynvaqpxybs .gt_super { font-size: 65%; }
 #ynvaqpxybs .gt_footnote_marks { font-size: 75%; vertical-align: 0.4em; position: initial; }
 #ynvaqpxybs .gt_asterisk { font-size: 100%; vertical-align: 0; }
 
</style>

<table class="gt_table caption-top table table-sm table-striped small" data-quarto-bootstrap="false">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="gt_heading header">
<td colspan="4" class="gt_heading gt_title gt_font_normal"><b>
Completed tutorial?</b></td>
</tr>
<tr class="gt_col_headings even">
<th id="Variant" class="gt_col_heading gt_columns_bottom_border gt_left" data-quarto-table-cell-role="th" scope="col">Variant</th>
<th id="Yes" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col">Yes</th>
<th id="No" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col">No</th>
<th id="Total" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" style="font-weight: bold" scope="col"><b>
Total</b></th>
</tr>
</thead>
<tbody class="gt_table_body">
<tr class="odd">
<td class="gt_row gt_left">Control</td>
<td class="gt_row gt_right">36,268</td>
<td class="gt_row gt_right">13,629</td>
<td class="gt_row gt_right" style="font-weight: bold">49,897</td>
</tr>
<tr class="even">
<td class="gt_row gt_left">Variant 1</td>
<td class="gt_row gt_right">38,280</td>
<td class="gt_row gt_right">11,995</td>
<td class="gt_row gt_right" style="font-weight: bold">50,275</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" style="font-weight: bold">Total</td>
<td class="gt_row gt_right" style="font-weight: bold">74,548</td>
<td class="gt_row gt_right" style="font-weight: bold">25,624</td>
<td class="gt_row gt_right" style="font-weight: bold; font-weight: bold">100,172</td>
</tr>
</tbody>
</table>


</div>
</div>
</div>
<p>To use an online significance calculator, we need two values for each variant: the number of students who completed the action and the total number of students assigned to that variant. The Polars code to extract this information is straightforward. We first <code>filter</code> for “Welcome tutorial” in the <em>experiments</em> dataframes and <code>left join</code> with the <em>actions</em> dataframe after applying a <code>filter</code> for “Tutorial complete”. The <code>left join</code> ensures that students who did not complete the action are still included. Then we perform a <code>group_by</code> on <em>Variant</em> column and <code>count</code> how many students completed the tutorial. Finally, we compute the completion percentage by dividing the number of completers by the total number of students assigned to each variant:</p>
<div id="311d1ee6" class="cell" data-execution_count="8">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>(experiments</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a> .<span class="bu">filter</span>(pl.col(<span class="st">'Experiment'</span>) <span class="op">==</span> <span class="st">'Welcome tutorial'</span>)</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a> .join(actions.<span class="bu">filter</span>(pl.col(<span class="st">'Action'</span>) <span class="op">==</span> <span class="st">'Tutorial complete'</span>),</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>       on<span class="op">=</span><span class="st">'User_ID'</span>,</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>       how<span class="op">=</span><span class="st">'left'</span>)</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a> .group_by(<span class="st">'Variant'</span>)</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a> .agg(Total_Cohorted<span class="op">=</span>pl.col(<span class="st">'User_ID'</span>).count(),</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>      Completions<span class="op">=</span>pl.col(<span class="st">'Action'</span>).is_not_null().<span class="bu">sum</span>())</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a> .with_columns(Pct_Completed<span class="op">=</span>pl.col(<span class="st">'Completions'</span>) <span class="op">/</span> pl.col(<span class="st">'Total_Cohorted'</span>))</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="8">
<div><style>
.dataframe > thead > tr,
.dataframe > tbody > tr {
  text-align: right;
  white-space: pre-wrap;
}
</style>
<small>shape: (2, 4)</small>
<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">Variant</th>
<th data-quarto-table-cell-role="th">Total_Cohorted</th>
<th data-quarto-table-cell-role="th">Completions</th>
<th data-quarto-table-cell-role="th">Pct_Completed</th>
</tr>
<tr class="even">
<td>str</td>
<td>u32</td>
<td>u32</td>
<td>f64</td>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>"Control"</td>
<td>49897</td>
<td>36268</td>
<td>0.726857</td>
</tr>
<tr class="even">
<td>"Variant 1"</td>
<td>50275</td>
<td>38280</td>
<td>0.761412</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>We can see that Variant 1 produced more completions than the Control group, with 72.69% of students finishing compared to 76.14%. The natural next question is whether this difference is large enough to be considered statistically significant rather than the result of random variation. After entering these values into an online significance calculator, we find that Variant 1’s completion rate is statistically significant at the 95% confidence level as shown in <a href="#fig-chi-squared-test" class="quarto-xref">Figure&nbsp;<span>6.1</span></a>. Based on this result, Variant 1 is considered the winning experience.</p>
<div id="fig-chi-squared-test" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-chi-squared-test-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/chi-squared-test.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-chi-squared-test-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6.1: p-value check for chi-squared test at 95% confidence interval
</figcaption>
</figure>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>A 95% confidence level is a common benchmark, but it is not the only one used in practice. There is extensive discussion about how to interpret confidence levels, when to choose alternative thresholds, and how to adjust analyses when experiments compare multiple variants against a single control.</p>
</div>
</div>
<p>Binary-outcome experiments tend to follow a consistent workflow. First, determine how many users completed the action of interest in each variant. Next, count how many users were assigned to each group. While the Polars code required to extract these success counts can vary depending on how events are recorded, the overall approach remains consistent. With this foundation in place, we can now turn to experiments that involve continuous metrics.</p>
</section>
<section id="experiments-with-continuous-outcomes-the-t-test" class="level3" data-number="6.3.2">
<h3 data-number="6.3.2" class="anchored" data-anchor-id="experiments-with-continuous-outcomes-the-t-test"><span class="header-section-number">6.3.2</span> Experiments with Continuous Outcomes: The t-Test</h3>
<p>Many experiments focus on improving <em>continuous metrics</em> rather than simple yes-or-no outcomes. Continuous metrics can take on a wide range of values, such as total spending, time spent on a page, or the number of days a user engages with an app. Ecommerce companies often test changes to product pages or checkout flows to increase revenue. Media organizations may experiment with layouts or headlines to drive higher article consumption. App developers frequently run campaigns designed to encourage users to return more often.</p>
<p>In these experiments, the goal is to determine whether the average value of a metric differs between variants in a statistically significant way. The standard tool for this analysis is the <em>two-sample t-test</em>, which evaluates whether we can reject the null hypothesis that the two means are equal at a chosen confidence level, typically 95%. The test requires three inputs: the mean, the standard deviation, and the sample size. All three are straightforward to compute using Polars.</p>
<p>Let’s walk through an example using the XtraLesson data. Earlier, we examined whether the redesigned welcome tutorial increased the likelihood that students completed onboarding. Now we want to assess whether that same tutorial affected how much students spent on courses. Because the metric of interest is spending, we need to compute the mean and standard deviation of the amount spent for each variant.</p>
<p>We begin by <code>filter</code>ing the <em>experiments</em> dataframe for the “Welcome tutorial” experiment and then <code>left join</code>ing the <em>payments</em> dataframe to bring in spending data. A <code>left join</code> is essential because many students never make a purchase, yet they must still be included in the analysis. For students without payments, we replace missing values with 0 using <code>fill_null</code>. Since <code>mean</code> and <code>std</code> ignore nulls, this step ensures that non-purchasers are counted correctly. Finally, we <code>group_by</code> the <em>Variant</em> column to compute the mean, standard deviation, and total number of students in each variant.</p>
<div id="7d3737e4" class="cell" data-execution_count="10">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>(experiments</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a> .<span class="bu">filter</span>(pl.col(<span class="st">'Experiment'</span>) <span class="op">==</span> <span class="st">'Welcome tutorial'</span>)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a> .join(payments, on<span class="op">=</span><span class="st">'User_ID'</span>, how<span class="op">=</span><span class="st">'left'</span>)</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a> .group_by(<span class="st">'Variant'</span>,<span class="st">'User_ID'</span>)</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a> .agg(Amount<span class="op">=</span>pl.col(<span class="st">'Amount'</span>).fill_null(<span class="dv">0</span>).<span class="bu">sum</span>())</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a> .group_by(<span class="st">'Variant'</span>)</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a> .agg(Total_Cohorted<span class="op">=</span>pl.col(<span class="st">'User_ID'</span>).count(),</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>      Mean_Amount<span class="op">=</span>pl.col(<span class="st">'Amount'</span>).mean(),</span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>      Std_Amount<span class="op">=</span>pl.col(<span class="st">'Amount'</span>).std())</span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="10">
<div><style>
.dataframe > thead > tr,
.dataframe > tbody > tr {
  text-align: right;
  white-space: pre-wrap;
}
</style>
<small>shape: (2, 4)</small>
<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">Variant</th>
<th data-quarto-table-cell-role="th">Total_Cohorted</th>
<th data-quarto-table-cell-role="th">Mean_Amount</th>
<th data-quarto-table-cell-role="th">Std_Amount</th>
</tr>
<tr class="even">
<td>str</td>
<td>u32</td>
<td>f64</td>
<td>f64</td>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>"Variant 1"</td>
<td>50275</td>
<td>3.687589</td>
<td>19.220194</td>
</tr>
<tr class="even">
<td>"Control"</td>
<td>49897</td>
<td>3.781218</td>
<td>18.940378</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>After entering these values into an online t-test calculator, we find no statistically significant difference in spending between the control group and Variant 1 at the 95% confidence level as shown in <a href="#fig-t-test" class="quarto-xref">Figure&nbsp;<span>6.2</span></a>. Variant 1 improved tutorial completion, but it did not increase the <em>Amount</em> spent.</p>
<div id="fig-t-test" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-t-test-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/t-test.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-t-test-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6.2: p-value check for t-test at 95% confidence interval
</figcaption>
</figure>
</div>
<p>A related question is whether Variant 1 influenced spending among students who actually completed the tutorial. Students who never finish onboarding do not enroll in courses and therefore make no purchases. To focus only on students who completed the tutorial, we use a similar approach but add an <code>inner join</code> to the <em>actions</em> dataframe. This restricts the dataset to students with a “Tutorial complete” event:</p>
<div id="978b3f78" class="cell" data-execution_count="11">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>(experiments</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a> .<span class="bu">filter</span>(pl.col(<span class="st">'Experiment'</span>) <span class="op">==</span> <span class="st">'Welcome tutorial'</span>)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a> .join(actions.<span class="bu">filter</span>(pl.col(<span class="st">'Action'</span>) <span class="op">==</span> <span class="st">'Tutorial complete'</span>),</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>       on<span class="op">=</span><span class="st">'User_ID'</span>,</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>       how<span class="op">=</span><span class="st">'inner'</span>)</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a> .join(payments, on<span class="op">=</span><span class="st">'User_ID'</span>, how<span class="op">=</span><span class="st">'left'</span>)</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a> .group_by(<span class="st">'Variant'</span>, <span class="st">'User_ID'</span>)</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a> .agg(Amount<span class="op">=</span>pl.col(<span class="st">'Amount'</span>).fill_null(<span class="dv">0</span>).<span class="bu">sum</span>())</span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a> .group_by(<span class="st">'Variant'</span>)</span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a> .agg(Total_Cohorted<span class="op">=</span>pl.col(<span class="st">'User_ID'</span>).count(),</span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a>      Mean_Amount<span class="op">=</span>pl.col(<span class="st">'Amount'</span>).mean(),</span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a>      Std_Amount<span class="op">=</span>pl.col(<span class="st">'Amount'</span>).std())</span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="11">
<div><style>
.dataframe > thead > tr,
.dataframe > tbody > tr {
  text-align: right;
  white-space: pre-wrap;
}
</style>
<small>shape: (2, 4)</small>
<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">Variant</th>
<th data-quarto-table-cell-role="th">Total_Cohorted</th>
<th data-quarto-table-cell-role="th">Mean_Amount</th>
<th data-quarto-table-cell-role="th">Std_Amount</th>
</tr>
<tr class="even">
<td>str</td>
<td>u32</td>
<td>f64</td>
<td>f64</td>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>"Variant 1"</td>
<td>38280</td>
<td>4.843091</td>
<td>21.899284</td>
</tr>
<tr class="even">
<td>"Control"</td>
<td>36268</td>
<td>5.202146</td>
<td>22.048994</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>When we test these values, the control group shows a statistically significantly higher average spend than Variant 1 at the 95% confidence level. Although this result may seem counterintuitive, it illustrates why defining the success metric before running an experiment is critical. Variant 1 clearly improved tutorial completion, so by that measure the experiment succeeded. However, it did not increase overall revenue. One possible explanation is a change in the composition of students: the additional students who completed onboarding in Variant 1 may have been less likely to purchase additional courses. If the original hypothesis was that improving onboarding completion would increase revenue, this experiment did not support that assumption, suggesting that the product team may need to explore alternative approaches.</p>
</section>
</section>
<section id="challenges-with-experiments-and-options-for-rescuing-flawed-experiments" class="level2" data-number="6.4">
<h2 data-number="6.4" class="anchored" data-anchor-id="challenges-with-experiments-and-options-for-rescuing-flawed-experiments"><span class="header-section-number">6.4</span> Challenges with Experiments and Options for Rescuing Flawed Experiments</h2>
<p>Although controlled experiments are the most reliable way to understand causal relationships, many things can still go wrong. When the underlying idea behind a test is fundamentally incorrect, there is little Polars or any other tool can do to repair it. However, when problems arise from technical mishaps, it is sometimes possible to reshape or filter the data so that at least part of the experiment remains interpretable. Experiments also require substantial investment from engineers, designers, and marketers who build and maintain variants. They carry <em>opportunity cost</em> as well, or the lost value that could have been captured by guiding customers through a more effective conversion journey or product experience. In practice, using Polars to extract whatever insights remain is often a worthwhile effort.</p>
<section id="variant-assignment" class="level3" data-number="6.4.1">
<h3 data-number="6.4.1" class="anchored" data-anchor-id="variant-assignment"><span class="header-section-number">6.4.1</span> Variant Assignment</h3>
<p>Random assignment of units, such as users, sessions, or other identifiers, to control and treatment groups is central to experimentation. Still, mistakes can occur due to a misconfigured test, a system outage, or limitations in the cohorting tool. When this happens, groups may become imbalanced, fewer entities may be assigned than expected, or the assignment process may not be random at all.</p>
<p>Polars can sometimes help recover an experiment in which too many units were assigned. For example, an experiment intended only for first time visitors may accidentally include the entire user base. A similar issue arises when the tested feature is visible only to a subset of users, perhaps because it appears deep in the product flow or requires a prior action such as completing a profile. Technical constraints may cause everyone to be cohorted even though many participants could never encounter the treatment. In these cases, adding a <code>join</code> that restricts the dataset to the intended eligible population can help. For a new user experiment, this might involve an <code>inner join</code> with a dataset containing account creation dates, followed by a <code>filter</code> that removes users who registered long before the cohorting event. The same pattern applies when eligibility depends on a prerequisite action. After narrowing the dataset, it is important to confirm that the remaining sample is still large enough to support meaningful statistical conclusions.</p>
<p>When too few entities are cohorted, the first step is to verify whether the sample size is adequate. If it is not, the experiment should be rerun. If the sample is technically large enough, the next question is whether the assignment process introduced bias. For example, I have encountered situations where users accessing the product through corporate networks with strict security settings were never assigned to any variant because the cohorting script failed to load. If the excluded group differs systematically, perhaps by geography, technical environment, or organizational context, it is important to assess its size and consider whether adjustments are needed before interpreting results.</p>
<p>Another potential issue is a flawed assignment mechanism that fails to randomize properly. This is rare with modern experimentation platforms, but when it occurs, the entire test becomes invalid. Extremely strong or suspiciously clean results can be a warning sign. I have seen cases where a configuration change caused highly active users to be placed into both control and treatment groups simultaneously. Careful data checks can reveal whether entities appear in multiple variants or whether pre experiment engagement levels are unevenly distributed across groups.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>Running an A/A test is a useful way to detect problems in the assignment system. In an A/A test, entities are cohorted as usual and metrics are compared, but both groups receive the exact same experience. Because nothing differs between the cohorts, we should observe no statistically significant differences. If a gap appears, it signals that the assignment logic needs investigation and correction.</p>
</div>
</div>
</section>
</section>
<section id="outliers" class="level2" data-number="6.5">
<h2 data-number="6.5" class="anchored" data-anchor-id="outliers"><span class="header-section-number">6.5</span> Outliers</h2>
<p>Statistical methods for continuous metrics rely heavily on averages, which makes them sensitive to extreme values. It is not uncommon for a single unusually high value customer to make a variant appear significantly better than it truly is. Without those outliers, the result might be neutral or even reversed. In most cases, the goal is to understand how a treatment affects typical users, so adjusting for outliers often leads to more reliable conclusions.</p>
<p>Anomaly detection was covered in <a href="./Anomaly Detection.html" target="_blank">Chapter 5</a>, and the same ideas apply here. Outliers can be identified by examining the experiment data directly or by comparing results to pre experiment baselines. Techniques such as winsorizing, also discussed in <a href="./Anomaly Detection.html" target="_blank">Chapter 5</a>, can trim values beyond a chosen percentile, such as the 95th or 99th. This preprocessing step can be performed in Polars before continuing with the analysis.</p>
<p>Another approach is to convert a continuous metric into a binary one. Instead of comparing average spend, which may be distorted by a few extreme purchasers, you can compare purchase rates between variants and then follow the procedures for binary outcomes. For example, consider the proportion of students who made a purchase after completing onboarding in the Control and Variant 1 groups of the “Welcome tutorial” experiment:</p>
<div id="b21f0c0e" class="cell" data-execution_count="12">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>(experiments</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a> .<span class="bu">filter</span>(pl.col(<span class="st">'Experiment'</span>) <span class="op">==</span> <span class="st">'Welcome tutorial'</span>)</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a> .join(actions.<span class="bu">filter</span>(pl.col(<span class="st">'Action'</span>) <span class="op">==</span> <span class="st">'Tutorial complete'</span>),</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>       on<span class="op">=</span><span class="st">'User_ID'</span>,</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>       how<span class="op">=</span><span class="st">'inner'</span>)</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a> .join(payments, on<span class="op">=</span><span class="st">'User_ID'</span>, how<span class="op">=</span><span class="st">'left'</span>)</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a> .group_by(<span class="st">'Variant'</span>, <span class="st">'User_ID'</span>)</span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a> .agg(Amount<span class="op">=</span>pl.col(<span class="st">'Amount'</span>).fill_null(<span class="dv">0</span>).<span class="bu">sum</span>())</span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a> .group_by(<span class="st">'Variant'</span>)</span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a> .agg(Total_Cohorted<span class="op">=</span>pl.col(<span class="st">'User_ID'</span>).count(),</span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a>      Buyers<span class="op">=</span>pl.col(<span class="st">'Amount'</span>).<span class="bu">filter</span>(pl.col(<span class="st">'Amount'</span>) <span class="op">&gt;</span> <span class="dv">0</span>).count(),</span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a>      Pct_Buyers<span class="op">=</span>pl.col(<span class="st">'Amount'</span>).<span class="bu">filter</span>(pl.col(<span class="st">'Amount'</span>) <span class="op">&gt;</span> <span class="dv">0</span>).count() <span class="op">/</span> pl.col(<span class="st">'User_ID'</span>).count())</span>
<span id="cb12-13"><a href="#cb12-13" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="12">
<div><style>
.dataframe > thead > tr,
.dataframe > tbody > tr {
  text-align: right;
  white-space: pre-wrap;
}
</style>
<small>shape: (2, 4)</small>
<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">Variant</th>
<th data-quarto-table-cell-role="th">Total_Cohorted</th>
<th data-quarto-table-cell-role="th">Buyers</th>
<th data-quarto-table-cell-role="th">Pct_Buyers</th>
</tr>
<tr class="even">
<td>str</td>
<td>u32</td>
<td>u32</td>
<td>f64</td>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>"Variant 1"</td>
<td>38280</td>
<td>4981</td>
<td>0.13012</td>
</tr>
<tr class="even">
<td>"Control"</td>
<td>36268</td>
<td>4988</td>
<td>0.137532</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>From these results, we can see that although Variant 1 includes more students overall, it has fewer purchasers. The Control group shows a 13.75% purchase rate, while Variant 1 is at 13.01%. After entering these values into an online calculator, the Control group’s conversion rate is statistically significantly higher as shown in <a href="#fig-chi-squared-test-2" class="quarto-xref">Figure&nbsp;<span>6.3</span></a>. Even so, the organization might still accept a small decline in purchases if the treatment meaningfully increases onboarding completion. Improvements in onboarding can boost rankings or generate more word of mouth referrals, both of which may drive long term growth.</p>
<div id="fig-chi-squared-test-2" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-chi-squared-test-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/chi-squared-test-2.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-chi-squared-test-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6.3: p-value check for chi-squared test at 95% confidence interval
</figcaption>
</figure>
</div>
<p>Success metrics can also be defined using thresholds, with analysis focused on the share of entities that meet those thresholds. For instance, a metric might indicate whether a learner completes a module or logs in at least twice per week. There are many ways to construct such measures, so it is essential to choose metrics that genuinely reflect what matters to the organization.</p>
<section id="time-boxing" class="level3" data-number="6.5.1">
<h3 data-number="6.5.1" class="anchored" data-anchor-id="time-boxing"><span class="header-section-number">6.5.1</span> Time Boxing</h3>
<p>Experiments often span multiple weeks. As a result, participants who enter earlier naturally have more time to complete behaviors tied to the primary metric. To reduce this imbalance, analysts can introduce <em>time boxing</em>, which defines a fixed observation window that begins at each participant’s entry point and counts only the activity that occurs within that window.</p>
<p>The ideal length of a time box depends on the behavior being measured. If the outcome occurs almost immediately, such as clicking an advertisement, the window might be as short as an hour. For purchase-related metrics, a window between 1 and 7 days is common. Shorter windows also allow analysts to review results sooner, since every entity must be given the full allotted time to act before evaluation. The goal is to select a window that reflects both the organization’s operational constraints and the natural timing of user behavior. For example, if most customers convert within a few days, a 7-day window is reasonable. If conversions typically take several weeks, a 30-day window may be more appropriate.</p>
<p>To illustrate, we can modify the earlier continuous-outcome example by restricting purchases to those made within 7 days of cohort assignment. It is critical that the time box begins at the moment the user is assigned to a variant:</p>
<div id="2bfc96ff" class="cell" data-execution_count="14">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>(experiments</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a> .<span class="bu">filter</span>(pl.col(<span class="st">'Experiment'</span>) <span class="op">==</span> <span class="st">'Welcome tutorial'</span>)</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a> .join(payments, on<span class="op">=</span><span class="st">'User_ID'</span>, how<span class="op">=</span><span class="st">'left'</span>)</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a> .with_columns(pl.when(pl.col(<span class="st">'Pay_Date'</span>) <span class="op">&lt;=</span> pl.col(<span class="st">'Date'</span>) <span class="op">+</span> pl.duration(days<span class="op">=</span><span class="dv">7</span>))</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>               .then(pl.col(<span class="st">'Amount'</span>))</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>               .otherwise(<span class="dv">0</span>)</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>               .alias(<span class="st">'Valid_Amount'</span>))</span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a> .group_by(<span class="st">'Variant'</span>, <span class="st">'User_ID'</span>)</span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a> .agg(Amount<span class="op">=</span>pl.col(<span class="st">'Valid_Amount'</span>).<span class="bu">sum</span>())</span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a> .group_by(<span class="st">'Variant'</span>)</span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a> .agg(Total_Cohorted<span class="op">=</span>pl.col(<span class="st">'User_ID'</span>).count(),</span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a>      Mean_Amount<span class="op">=</span>pl.col(<span class="st">'Amount'</span>).mean(),</span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a>      Std_Amount<span class="op">=</span>pl.col(<span class="st">'Amount'</span>).std())</span>
<span id="cb13-14"><a href="#cb13-14" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="14">
<div><style>
.dataframe > thead > tr,
.dataframe > tbody > tr {
  text-align: right;
  white-space: pre-wrap;
}
</style>
<small>shape: (2, 4)</small>
<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">Variant</th>
<th data-quarto-table-cell-role="th">Total_Cohorted</th>
<th data-quarto-table-cell-role="th">Mean_Amount</th>
<th data-quarto-table-cell-role="th">Std_Amount</th>
</tr>
<tr class="even">
<td>str</td>
<td>u32</td>
<td>f64</td>
<td>f64</td>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>"Variant 1"</td>
<td>50275</td>
<td>1.351688</td>
<td>5.612986</td>
</tr>
<tr class="even">
<td>"Control"</td>
<td>49897</td>
<td>1.369382</td>
<td>5.766338</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>The resulting averages remain close to one another, and the differences are not statistically significant. In this case, the conclusion reached with time boxing matches the conclusion reached without it.</p>
<p>Because purchases occur relatively infrequently, the impact of time boxing is modest in this example. For metrics that accumulate quickly, such as pageviews, clicks, likes, or articles read, time boxing plays a much more important role. It prevents early entrants from appearing disproportionately successful simply because they had more time to generate activity.</p>
</section>
<section id="repeated-exposure-experiments" class="level3" data-number="6.5.2">
<h3 data-number="6.5.2" class="anchored" data-anchor-id="repeated-exposure-experiments"><span class="header-section-number">6.5.2</span> Repeated Exposure Experiments</h3>
<p>In discussions of online experimentation, many examples involve what can be described as “one-and-done” interactions. The user encounters the treatment once, responds to it, and does not revisit that experience. Account creation is a typical example. Users register only a single time, so changes to the registration flow affect only new sign-ups. These experiments are usually straightforward to analyze.</p>
<p>A different category involves <em>repeated exposure</em> experiences, where users encounter the change multiple times as they continue using a product or service. In these experiments, individuals are expected to see the treatment repeatedly. Changes to an app’s interface, such as adjustments to colors, text, or the placement of key elements, are experienced throughout ongoing usage. Similarly, recurring email campaigns expose customers to subject lines and message content over many interactions.</p>
<p>Repeated-exposure experiments are more challenging to evaluate because of novelty effects and regression to the mean. A <em>novelty effect</em> occurs when behavior changes simply because something appears new, not because it is inherently better. <em>Regression to the mean</em> describes the tendency for metrics to drift back toward typical levels over time. For example, changing a user interface element often increases engagement initially. Users may click more on a new button color or layout. That early lift reflects novelty. As users become accustomed to the change, engagement often settles closer to its original level, demonstrating regression. The key question is whether the long-term level ultimately ends up higher or lower than before. One common approach is to wait long enough for the novelty to fade, which may take days, weeks, or even months, before drawing conclusions.</p>
<p>When many changes occur, or when treatments are delivered sequentially, such as in recurring email or direct-mail campaigns, assessing overall impact becomes even more difficult. It can be tempting to attribute a purchase to a specific email variant, but the customer may have purchased regardless. One strategy is to create a <em>long-term holdout</em> group that receives no marketing messages or product experience changes. This approach differs from observing users who opt out of marketing, since opt-out behavior is not random and introduces bias. Although long-term holdouts can be operationally challenging, they provide one of the clearest ways to measure cumulative program effects.</p>
<p>Another option is to perform cohort analyses across variants. By tracking groups over extended periods, such as weeks or months, analysts can compute retention or cumulative metrics and compare long-term differences between treatments.</p>
<p>Despite these complexities, experimentation remains the strongest method for establishing causal relationships across domains ranging from marketing communications to in-product design. In practice, however, real-world constraints sometimes prevent ideal A/B testing. In the next section, we will explore analytical techniques for situations where controlled experiments are not feasible.</p>
</section>
</section>
<section id="when-controlled-experiments-arent-possible-alternative-analyses" class="level2" data-number="6.6">
<h2 data-number="6.6" class="anchored" data-anchor-id="when-controlled-experiments-arent-possible-alternative-analyses"><span class="header-section-number">6.6</span> When Controlled Experiments Aren’t Possible: Alternative Analyses</h2>
<p>Randomized experiments remain the strongest tool for moving from correlation to credible causal inference. However, there are many situations in which running such an experiment is not feasible. Ethical concerns may prevent assigning different treatments to different groups, particularly in domains such as healthcare or education. Regulatory constraints can also limit experimentation in industries like finance. In other cases, practical limitations make experimentation unrealistic, such as when it is impossible to restrict access to a new experience to only a randomized subset of users. Even in these situations, it is often worth considering whether smaller components, such as copy, layout, or specific design choices, can still be tested within acceptable boundaries.</p>
<p>Another common scenario occurs when a change has already been implemented and data collection is complete. Unless the organization is willing to revert the change, it is impossible to run a proper experiment retroactively. This often happens because no analyst was available to advise on experimental design at the time. I have worked with teams that later needed help interpreting the impact of changes that would have been much easier to evaluate if a holdout group had been created. In other cases, the change was unintentional. Examples include partial site outages, form errors, or large external disruptions such as storms or wildfires.</p>
<p>Although causal claims are weaker without randomization, several quasi-experimental approaches can still yield useful insights. These methods attempt to construct comparison groups from existing data that approximate control and treatment conditions as closely as possible.</p>
<section id="pre-post-analysis" class="level3" data-number="6.6.1">
<h3 data-number="6.6.1" class="anchored" data-anchor-id="pre-post-analysis"><span class="header-section-number">6.6.1</span> Pre-/Post-Analysis</h3>
<p>A pre-/post-analysis compares outcomes for the same population, or a very similar one, before and after a specific change. The period before the change serves as the control, while the period after the change acts as the treatment.</p>
<p>This approach works best when the change occurs at a clearly identifiable point in time, allowing the data to be cleanly divided into “before” and “after” segments. You must also decide how long each window should be, and the two windows should be roughly equal in duration. For example, if two weeks have passed since the change, you might compare those two weeks with the two weeks immediately preceding it. It can be helpful to examine multiple window lengths, such as one week, two weeks, three weeks, and four weeks, to assess whether conclusions are consistent across them.</p>
<p>Consider the following example. Suppose the onboarding flow for XtraLesson includes a checkbox that allows students to opt in to course-related emails. Historically, this box was checked by default, but a new regulation requires it to be unchecked. The update went live on January 27, 2024, and we want to assess whether this change reduced the email opt-in rate. We compare the two weeks before the change with the two weeks after it. A two-week window is long enough to smooth out day-of-week effects while remaining short enough to limit the influence of unrelated factors.</p>
<p>In the Polars code below, variants are assigned using a <code>when-then-otherwise</code> expression. Students enrolled before the cutoff date are labeled “pre,” and those enrolled afterward are labeled “post.” We then perform a <code>left join</code> with the <em>actions</em> dataframe, filtering to the “Email opt-in” action. Finally, we <code>group_by</code> <em>Variant</em> and compute metrics including the number of students in each group, the number of opt-ins, and the opt-in rate. I also include the number of distinct enrollment days in each group as a quality check:</p>
<div id="d83ded1e" class="cell" data-execution_count="15">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>(students</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a> .<span class="bu">filter</span>(pl.col(<span class="st">'Enroll_Date'</span>).is_between(pl.date(<span class="dv">2024</span>,<span class="dv">1</span>,<span class="dv">13</span>), pl.date(<span class="dv">2024</span>,<span class="dv">2</span>,<span class="dv">9</span>)))</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a> .with_columns(pl.when(pl.col(<span class="st">'Enroll_Date'</span>).is_between(pl.date(<span class="dv">2024</span>, <span class="dv">1</span>, <span class="dv">13</span>), pl.date(<span class="dv">2024</span>,<span class="dv">1</span>,<span class="dv">26</span>)))</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>               .then(pl.lit(<span class="st">'pre'</span>))</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>               .when(pl.col(<span class="st">'Enroll_Date'</span>).is_between(pl.date(<span class="dv">2024</span>,<span class="dv">1</span>,<span class="dv">27</span>), pl.date(<span class="dv">2024</span>,<span class="dv">2</span>,<span class="dv">9</span>)))</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>               .then(pl.lit(<span class="st">'post'</span>))</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>               .otherwise(<span class="va">None</span>)</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>               .alias(<span class="st">'Variant'</span>))</span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a> .join(actions.<span class="bu">filter</span>(Action<span class="op">=</span><span class="st">'Email opt-in'</span>), on<span class="op">=</span><span class="st">'User_ID'</span>, how<span class="op">=</span><span class="st">'left'</span>)</span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a> .group_by(<span class="st">'Variant'</span>)</span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a> .agg(Cohorted<span class="op">=</span>pl.col(<span class="st">'User_ID'</span>).n_unique(),</span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a>      Opted_In<span class="op">=</span>pl.col(<span class="st">'Action'</span>).is_not_null().<span class="bu">sum</span>(),</span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a>      Pct_Optin<span class="op">=</span>(pl.col(<span class="st">'Action'</span>).is_not_null().<span class="bu">sum</span>() <span class="op">/</span> pl.col(<span class="st">'User_ID'</span>).n_unique()),</span>
<span id="cb14-14"><a href="#cb14-14" aria-hidden="true" tabindex="-1"></a>      Days<span class="op">=</span>pl.col(<span class="st">'Enroll_Date'</span>).n_unique())</span>
<span id="cb14-15"><a href="#cb14-15" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="15">
<div><style>
.dataframe > thead > tr,
.dataframe > tbody > tr {
  text-align: right;
  white-space: pre-wrap;
}
</style>
<small>shape: (2, 5)</small>
<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">Variant</th>
<th data-quarto-table-cell-role="th">Cohorted</th>
<th data-quarto-table-cell-role="th">Opted_In</th>
<th data-quarto-table-cell-role="th">Pct_Optin</th>
<th data-quarto-table-cell-role="th">Days</th>
</tr>
<tr class="even">
<td>str</td>
<td>u32</td>
<td>u32</td>
<td>f64</td>
<td>u32</td>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>"pre"</td>
<td>24662</td>
<td>14489</td>
<td>0.587503</td>
<td>14</td>
</tr>
<tr class="even">
<td>"post"</td>
<td>27617</td>
<td>11220</td>
<td>0.406271</td>
<td>14</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>The results show that students in the “pre” period opted in at a much higher rate, 58.75%, than those in the “post” period, 40.63%. An online significance test confirms that this difference is statistically significant. Because the change was mandated, XtraLesson may not be able to revert it. However, future experiments could explore whether providing additional context or examples encourages more students to opt in.</p>
<p>When using pre-/post-analysis, it is important to remember that many forces unrelated to the change can influence the metric. Seasonal effects, external events, and marketing activity can all shift user behavior, even over short time horizons. For this reason, pre-/post-analysis is weaker than a randomized experiment for establishing causality. Still, it can be a valuable technique when experimentation is not possible and can help generate hypotheses for future controlled studies.</p>
</section>
<section id="natural-experiment-analysis" class="level3" data-number="6.6.2">
<h3 data-number="6.6.2" class="anchored" data-anchor-id="natural-experiment-analysis"><span class="header-section-number">6.6.2</span> Natural Experiment Analysis</h3>
<p>A <em>natural experiment</em> occurs when different groups are exposed to distinct conditions due to circumstances that resemble random assignment. One group experiences the standard or control scenario, while another encounters an unintended variation that may affect outcomes positively or negatively. These situations often arise unexpectedly, such as from a software bug or an external event that impacts only certain regions. For the analysis to be credible, we must clearly identify which entities were exposed to the altered condition and establish a comparison group that closely resembles them.</p>
<p>Polars can be used to construct these variants and compute cohort sizes along with outcome metrics, such as counts of successes for binary outcomes or summary statistics like the mean, standard deviation, and sample size for continuous outcomes. Once calculated, these values can be entered into an online statistical calculator just as they would be for a traditional experiment.</p>
<p>To illustrate this approach using the XtraLesson datasets, suppose that during the analysis window, Canadian students unintentionally saw an incorrect offer when they first opened the course catalog. Each bundle displayed an extra zero in the number of included courses. A bundle intended to show 1 course appeared as 10, while a bundle with 5 courses appeared as 50, and so on.</p>
<p>Our objective is to determine whether this error caused Canadian students to enroll in paid courses at a higher rate than students elsewhere. Rather than comparing Canada to all other countries, we limit the comparison to the United States. The two countries are geographically close, share a common language for most learners, and, based on earlier analysis, exhibit similar learning and purchasing behavior. Students from other regions differ enough that including them would introduce unnecessary variability, so they are excluded from this comparison.</p>
<p>To perform the analysis, we define the variants based on the distinguishing feature, which in this case is the <em>Country</em> column in the <em>students</em> dataframe. Depending on the dataset, more complex Polars code may be necessary. However, the overall strategy mirrors earlier examples: count the number of students in each cohort and the number who made a purchase.</p>
<div id="cfb3c274" class="cell" data-execution_count="17">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>(students</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a> .<span class="bu">filter</span>(pl.col(<span class="st">'Country'</span>).is_in([<span class="st">'United States'</span>, <span class="st">'Canada'</span>]))</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a> .join(payments, on<span class="op">=</span><span class="st">'User_ID'</span>, how<span class="op">=</span><span class="st">'left'</span>)</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a> .group_by(<span class="st">'Country'</span>, <span class="st">'User_ID'</span>)</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a> .agg(Amount<span class="op">=</span>pl.col(<span class="st">'Amount'</span>).fill_null(<span class="dv">0</span>).<span class="bu">sum</span>())</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a> .group_by(<span class="st">'Country'</span>)</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a> .agg(Total_Cohorted<span class="op">=</span>pl.col(<span class="st">'User_ID'</span>).count(),</span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>      Purchasers<span class="op">=</span>pl.col(<span class="st">'Amount'</span>).<span class="bu">filter</span>(pl.col(<span class="st">'Amount'</span>) <span class="op">&gt;</span> <span class="dv">0</span>).count(),</span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>      Pct_Purchased<span class="op">=</span>(pl.col(<span class="st">'Amount'</span>).<span class="bu">filter</span>(pl.col(<span class="st">'Amount'</span>) <span class="op">&gt;</span> <span class="dv">0</span>).count() <span class="op">/</span> pl.count(<span class="st">'User_ID'</span>)))</span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="17">
<div><style>
.dataframe > thead > tr,
.dataframe > tbody > tr {
  text-align: right;
  white-space: pre-wrap;
}
</style>
<small>shape: (2, 4)</small>
<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">Country</th>
<th data-quarto-table-cell-role="th">Total_Cohorted</th>
<th data-quarto-table-cell-role="th">Purchasers</th>
<th data-quarto-table-cell-role="th">Pct_Purchased</th>
</tr>
<tr class="even">
<td>str</td>
<td>u32</td>
<td>u32</td>
<td>f64</td>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>"United States"</td>
<td>45012</td>
<td>4958</td>
<td>0.110148</td>
</tr>
<tr class="even">
<td>"Canada"</td>
<td>20179</td>
<td>5011</td>
<td>0.248327</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>The proportion of Canadian students who made a purchase is higher at 24.83%, compared with 11.01% for U.S. students. Entering these values into an online statistical calculator indicates that the Canadian conversion rate is significantly higher at the 95% confidence level as shown in <a href="#fig-chi-squared-test-3" class="quarto-xref">Figure&nbsp;<span>6.4</span></a>.</p>
<div id="fig-chi-squared-test-3" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-chi-squared-test-3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/chi-squared-test-3.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-chi-squared-test-3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6.4: p-value check for chi-squared test at 95% confidence interval
</figcaption>
</figure>
</div>
<p>One of the most difficult aspects of natural experiment analysis is demonstrating that the exposed and comparison groups are sufficiently similar to support valid statistical conclusions. While it is rarely possible to eliminate all confounding factors, examining demographic and behavioral similarities can strengthen the credibility of the results. Because natural experiments lack true randomization, any causal claims are inherently weaker and should be framed with appropriate caution.</p>
</section>
<section id="analysis-of-populations-around-a-threshold" class="level3" data-number="6.6.3">
<h3 data-number="6.6.3" class="anchored" data-anchor-id="analysis-of-populations-around-a-threshold"><span class="header-section-number">6.6.3</span> Analysis of Populations Around a Threshold</h3>
<p>In some settings, a specific cutoff determines who receives a treatment and who does not. A scholarship may require a minimum GPA, a subsidy might depend on household income, or a high churn risk score may trigger intervention from a sales representative. In these cases, individuals just above and just below the threshold are likely to be very similar. Instead of comparing all treated and untreated individuals, we can focus on those near the cutoff on both sides. This strategy is known as a <em>regression discontinuity design</em> (RDD).</p>
<p>To apply this method, we create variants by splitting the data around the threshold, similar to a pre- and post-analysis. There is no universal rule for selecting the width of the bands around the cutoff. The groups should be reasonably balanced in size and large enough to detect meaningful differences. Analysts often repeat the analysis using several bandwidths, such as including observations within 5%, 7.5%, and 10% of the threshold. Consistent results across these specifications increase confidence in the findings, while divergence suggests that the evidence may be inconclusive.</p>
<p>As with other observational methods, results from an RDD should be interpreted carefully when making causal claims. Potential confounding factors require close attention. For example, if high-risk customers receive multiple retention efforts, such as discounts or outreach from several teams, those additional actions may influence outcomes and complicate interpretation.</p>
</section>
</section>
<section id="conclusion" class="level2" data-number="6.7">
<h2 data-number="6.7" class="anchored" data-anchor-id="conclusion"><span class="header-section-number">6.7</span> Conclusion</h2>
<p>Experimental analysis encompasses a broad set of techniques, many of which connect to topics covered elsewhere in this book, including anomaly detection. Data profiling can help surface issues that affect interpretation. When randomized experiments are not feasible, several alternative strategies are available, and Polars can play a key role in constructing synthetic control and variant groups.</p>
<p>In the next chapter, we turn to assembling complex datasets for analysis, bringing together many of the concepts discussed so far.</p>


</section>
<section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p>See <a href="https://www.statisticshowto.com/probability-and-statistics/chi-square">https://www.statisticshowto.com/probability-and-statistics/chi-square</a> for a clear overview of the test.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./Anomaly Detection.html" class="pagination-link" aria-label="Anomaly Detection">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Anomaly Detection</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./Creating Complex Datasets for Analysis.html" class="pagination-link" aria-label="Creating Complex Datasets for Analysis">
        <span class="nav-page-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Creating Complex Datasets for Analysis</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>