---
title: "Adding a currency symbol to polars dataframe values"
author: '{{< var author >}}'
date: '2025-06-23'
date-format: iso
toc: true
toc-title: 'Sections'
toc-location: right
toc-depth: 3
categories: [100DaysOfPolars]
---

When your dataframe contains monetary values such as budgets it’s helpful to include a currency symbol. This ensures your audience clearly understands whether the figures are in dollars, euros, pounds, or another currency.

Below is an example of a dataframe that displays budget figures for each department at Duwata Company.

```{python}
#| echo: false

import polars as pl

df = pl.DataFrame({
    "Department": ["Hospitality", "Legal", "Finance", "Advertising", "Sales"],
    "Budget": [50000, 120000, 80000, 60000, 90000],
})

df
```


## Add currency to budget figures

If you were presenting these values to the American division of Duwata, you might want to include the dollar symbol in the *Budget* column values.

Here’s how you can do that using Polars.

```{python}
(df
 .select('Department','Budget')
 .with_columns(Budget=pl.format("${}", pl.col("Budget")))
 )
```

<br>
If you were presenting the data to Duwata’s European division and wanted to use the euro symbol instead, you would simply replace `$` with `€`.

```{python}
(df
 .select('Department','Budget')
 .with_columns(Budget=pl.format("€{}", pl.col("Budget")))
 )
```

<br>

::: {.callout-note}
Adding a currency symbol to the values in the *Budget* column converts the data type from numeric to string. As a result, you can no longer perform numeric operations like division on this column. This formatting change is meant purely for presentation purposes, such as displaying the data in a PowerPoint slide or a PDF document.
:::

Speed up your data analysis by enrolling in my {{< var polars_course >}}.