---
title: "Collapsing row values into a list in polars"
subtitle: "to_list"
author: '{{< var author >}}'
date: '2025-08-16'
date-format: iso
toc: true
toc-title: 'Sections'
toc-location: right
toc-depth: 3
categories: [100DaysOfPolars]
---

Python is big on lists because they are one of the fundamental data structures of the language. It’s no surprise that data analysis tasks in Python almost always involve using lists. Luckily, Polars allows you to collapse a series of rows into a list. Below is a dataframe showing sales from a clothing store.

```{python}
#| echo: false
import polars as pl
df = (pl.read_csv('https://raw.githubusercontent.com/jorammutenge/learn-rust/refs/heads/main/sample_sales.csv', try_parse_dates=True)
      .rename({'Account Name':'company', 'unit price':'price'})
      .select('category','quantity')
      )
df
```
<br>

## Get list of clothing categories

Suppose you want to know the unique categories of clothing available at this store and store those categories in a list. How would you do it in Polars? You simply use the method `to_list`, but it’s a series method, not a dataframe method. Therefore, you’ll need to convert the dataframe into a series.

```{python}
(df
 ['category']
 .unique()
 .to_list()
 )
```

## The idiomatic way

Subscribers to the idiomatic way of writing Polars code, like myself, would frown upon the use of square brackets in the code above. Let me show you how to rewrite the code above (without embarrassment) if you, too, want to be a Polars connoisseur.

```{python}
(df
 .select('category')
 .unique()
 .to_series()
 .to_list()
 )
```

Become a master of Polars my enrolling in my {{< var polars_course >}}.

